git:
  mainBranches:
    - master
    - main
    - develop

gui:
  theme:
    selectedLineBgColor:
      - "black"

  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: single

  nerdFontsVersion: "3"
  showBottomLine: true
