git:
  # pagers:
  #   - pager: delta --paging=never

  mainBranches:
    - master
    - main
    - develop

gui:
  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: single

  nerdFontsVersion: ""
  showBottomLine: true
